### ISSUE TITLE
Included systemd-tmpfile makes it impossible to use OpenSSH with keyfile authentication

### ISSUE THREAD

**Issue by Bernie-McGee** [Edenhofer/minecraft-server#10]
The line `z /srv/fabric 2775 fabric fabric - -` in the included file `/usr/lib/tmpfiles.d/minecraftd.conf` makes it impossible to utilize OpenSSH using keyfiles as the `minecraft` user. OpenSSH requires that the home directory and authorized_keys file have more restrictive permissions (see [here](https://wiki.archlinux.org/title/SSH_keys#Key_ignored_by_the_server)).

I have commented out that line, and server management seems to work with no issues. I have _not_ done extensive testing since the update that added the systemd-tmpfile, but I had the more restrictive directory permissions set prior to that update for quite some time with no issues.

**Comment by Edenhofer** [comment]
I think having more restrictive permissions makes a lot of sense. Fixed :)

I don't think we need a new release for this change assuming not too many people are affected (i.e. have their minecraft server user SSH into their machine). Thus, if you don't object, I would not create a new release just yet and not update the various Arch User Repository packages any time soon.

**Comment by Bernie-McGee** [comment]
That's great! I'll stick with keeping the systemd-tmpfile commented out until the next update. 

Thanks, as always!
