### ISSUE TITLE
restart fails if shutdown takes too long

### ISSUE THREAD

**Issue by alyxbb** [Edenhofer/minecraft-server#11]
If it takes too long for the server to shutdown then the server stopping will time out and the server will try to start while the game is still running causing the start to fail.

**Comment by Edenhofer** [comment]
I am not sure how to best address this. I don't want the script to wait indefinitely for the server to shut down. In case the server hangs, I want the script to timeout at some point. However, I can certainly increase the [current timeout of 10 seconds](https://github.com/Edenhofer/minecraft-server/blob/703d029/minecraftd.sh.in#L278) to something longer. How much time does your server need to shut down and what do you think about simply increasing the timeout?

**Comment by alyxbb** [comment]
It's taking about 30s but the server is quite slow, what about making the wait time configurable?

**Comment by Edenhofer** [comment]
f311d10 introcues `MAX_SERVER_STOP_TIME` that can be configured via the local environment and the config file. Can you try out the change and confirm that it works as intended?

**Comment by alyxbb** [comment]
lgtm
