### ISSUE TITLE
IDLE_SERVER problem with RegEx resulting in disconnect while Players are connected.

### ISSUE THREAD

**Issue by bigla** [Edenhofer/minecraft-server#3]
I installed this script via the AUR (arch linux user repository) and tried to config the server to idle if there is no player online using IDLE_SERVER=true and IDLE_IF_TIME=400 .

The first RegEx `s/.*\: //` seems to be greedy so everything until the last `:` will be replaced with nothing.

The content of my `$response` is:
```
list
[22:35:12 INFO]: There are 1 of a max of 20 players online: banen0r
>
```
Thus the command yields:

`0`

https://github.com/Edenhofer/minecraft-server/blob/ffd0e0b0b0f2b7d92bd8ce315d551ef1d89766f5/minecraftd.sh.in#L99

**Comment by bigla** [comment]
`grep "There are" | sed -r -e 's/.*There are //' | cut -d " " -f 1`

Yields the first number after "There are" for me. Maybe for all of us.

**Comment by Edenhofer** [comment]
Thank you very much for the report! The bug indeed seems to be in the line you pointed out.

Can you test whether the following works for you:
```bash
# Check whether there are player on the server through list
is_player_online() {
	response="$(sleep_time=0.6 return_stdout=true game_command list)"
	# Delete leading line and fancy characters from free response string
	response="$(echo "${response}" | sed -r -e 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[JKmsuG]//g')"
	# The list command prints a line containing the usernames after the last occurrence of ": "
	# and since playernames may not contain this string the clean player-list can easily be retrieved.
	# Otherwise check the first digit after the last occurrence of "There are". If it is 0 then there
	# are no players on the server. Should this test fail as well. Assume that a player is online.
	if [[ $(echo "${response}" | grep ":" | sed -e 's/.*\: //' | tr -d '\n' | wc -c) -le 1 ]]; then
		# No player is online
		return 0
	elif [[ "x$(echo "${response}" | grep -i "there are" | sed -r -e 's/.*there are[^0-9+]*([0-9]+).*$/\1/i' | tr -d '\n')" == "x0" ]]; then
		# No player is online
		return 0
	else
		# A player is online (or it could not be determined)
		return 1
	fi
}
```

I am a bit reluctant to simplify the regex too much because it might break the setup for different flavors of minecraft.

EDIT:
The second `sed`-line can be simplified like so:
```bash
[[ "x$(echo "${response}" | sed -n -r -e 's/.*there are[^0-9+]*([0-9]+).*$/\1/ip' | tr -d '\n')" == "x0" ]]
```

**Comment by bigla** [comment]
First version worked for me.

Testing the second sed-line.

EDIT:
Second sed-line working so far, no disconnects. 

Thank you for having a look into this so fast - you are helping to save energy a lot :)

**Comment by Edenhofer** [comment]
Thank you for the report and testing the new function! This was very productive!

For posterity's sake and anyone interested in why the idle server worked for them so far: The second RegEx had unintended matches for the vanilla minecraft server. Namely, the first number within the username string would be used as the player count. If no usernames on your servers had any numbers in them or if the first user on your server with a number had a non-zero one, then you were not affected.
