### ISSUE TITLE
Don't hard-code GAME_USER to GAME

### ISSUE THREAD

**Issue by Chais** [Edenhofer/minecraft-server#8]
I'm trying to adapt the `forge` AUR package for an older version of forge. Since the user is set to `GAME_USER` in the `.sysuser.in` file, I'd like to reuse the `forge` user from the `forge` package, as `forge-1.18.2` is not a valid user name.  
I suggest allowing the `GAME_USER` variable to be set manually, while keeping with `GAME` as a default value. Using `?=` instead of `=` in the Makefile should do the trick.

**Comment by Edenhofer** [comment]
Can you elaborate a little more. It would be phantastic if you could provide the command line used, the actual output and the desired output.

What you describe sounds an awful lot like what [spigot](https://aur.archlinux.org/packages/spigot) is already doing.

**Comment by Chais** [comment]
Actually, never mind. It turned out to be a left over config file. False alarm.
