### ISSUE TITLE
Cannot install two flavours of minecraft in the same machine

### ISSUE THREAD

**Issue by xdiban** [Edenhofer/minecraft-server#9]
When creating a fabric flavour installation and then a default minecraft installation, I receive the same output with both `fabricd` and `minecraftd`. If I `fabricd start` or `minecraftd start`, the fabric server starts with both commands. How can I make two differents servers on the same machine?

**Comment by xdiban** [comment]
I see the problem with /usr/bin/minecraftd

**Comment by Edenhofer** [comment]
Multiple servers can co-exists just fine. Please see https://github.com/Edenhofer/minecraft-server/tree/703d029358ceb830302c8337e3c088d4ec5ef8df#build-and-install-for-a-different-flavor-of-minecraft for instructions on how to configure multiple flavors of minecraft-servers.
